Run pytest after package installation
plotly/dash-ag-grid pull request #340
Opened 2024-11-21 21:03 UTC by ndrezn

For some reason on `release.yml`, tests were being run before packages were installed.

2024-11-21 21:05 UTC, gvwilson approved these changes

2024-11-21 21:08 UTC, BSd3v commented on package.json
Eh, I dont know about this.

This assumes that the dev wants to run tests before creating a distro. For example, what if I wanted to install it onto an app using `npm run dist`, I'd have to sit through the tests again.

2024-11-21 21:11 UTC, BSd3v requested changes

2024-11-21 21:11 UTC, BSd3v commented on .github/workflows/release.yml
>            npm pack && mv *.tgz dist/
```
npm i
npm run dist
pytest --headless
npm pack && mv *.tgz dist/
```

I'd just add the test there.

2024-11-21 21:11 UTC, ndrezn commented on package.json
I'll make it an optional step. I don't think we ever want to allow generating a dist without passing tests but we can enforce it in CI anyway.

2024-11-22 15:44 UTC, BSd3v approved these changes
💃

2024-11-22 15:45 UTC, merged